---
title: Aoife McArdle
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    image: 
    author: 
url: http://earnstudios.com
permalink: pretty
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- bower_components
description: Aoife McArdle is a writer/director/photographer from Northern Ireland, based in London
company: Aoife Mcardle
email: info@aoifemcardle.com
google_site_verification:
analytics:
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: 
  instagram: aoifemmcardle 
  twitter: aoife_mcardle
  vimeo: aoifemcardle