---
title: Aoife McArdle
timezone: UTC
collections:
  posts:
    title: Posts
    output: false
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://aoifemcardle.com
description: Aoife McArdle is a writer/director/photographer from Northern Ireland, based in London
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Aoife Mcardle
email: info@aoifemcardle.com
google_site_verification: 
analytics: UA-91296566-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: 
  instagram: https://www.instagram.com/aoifemmcardle
  twitter: https://twitter.com/aoife_mcardle
  vimeo: https://vimeo.com/aoifemcardle
